version: '3.9'

services:
  dialoqbase:
    build: 
      context: ../
      dockerfile: Dockerfile
    container_name: dialoqbase
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      DB_REDIS_URL: redis://redis:6379
    env_file:
      - .env
    depends_on:
      - dialoqbase-pg
      - redis
    volumes:
      - .uploads:/app/uploads

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - .redis:/data
